### ISSUE TITLE
il-repack doesn't work Akka.Net / Fsharp

### ISSUE THREAD

**Issue by nicolaserny** [gluck/il-repack#163]
I tried to write a basic F# lib based on akka (http://getakka.net/docs/FSharp%20API) and merged all the Akka dlls (and dependencies) with my lib.
The merged dll seems ok (no error in peverify).
But when I write a console app to test this lib, the Akka spawn function crashes with the following exception:

{System.ArgumentException: Expression of type 'Microsoft.FSharp.Core.Unit' cannot be used for parameter of type 'Microsoft.FSharp.Core.Unit' of method 'FunActor`2 Invoke(Microsoft.FSharp.Core.Unit)'
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression[] arguments)
   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.ConvExprToLinqInContext(ConvEnv env, FSharpExpr inp)
   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.ConvExprToLinqInContext(ConvEnv env, FSharpExpr inp)
   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.QuotationToLambdaExpression[T](FSharpExpr`1 e)
   at Akka.FSharp.Spawn.spawnOpt[Message,Returned](IActorRefFactory actorFactory, String name, FSharpFunc`2 f, FSharpList`1 options)   

My lib is just a basic function that creates an agent and posts a message to it (based on F# akka doc):
`
let testing() = 

        let testAgent = fun () ->
                spawn system (Guid.NewGuid().ToString())
                    (fun mailbox ->
                        let rec loop() = actor {
                           let! msg = mailbox.Receive()
                           mailbox.Sender() <! true
                           return! loop()
                        }
                        loop()                                                    
                        )     
        let ag = testAgent()
        let res = postAndReply<bool> ag 1000 "test"
        match res with
        | Some(t) when t = true -> printfn "ok"
        | None -> ()
`
Without dll merging, the previous code is working well.
Any ideas ?

Thanks,

**Comment by gluck** [comment]
You get this error because you merged FSharp core dll (containing `Microsoft.FSharp.Core.Unit`).
From this point on, code in your assembly is referencing the merged types, and are incompatible if you try to use this library together with code referencing the FSharp dll.
Usual course of action is to only merge "implementation detail assemblies", not the ones which participate (method argument, base type, method return type...) in the public API of your assembly.

**Comment by nicolaserny** [comment]
Thanks for your quick answer. Indeed, without merging FSharp.Core.dll, it's working :)
