### ISSUE TITLE
Invalid project file during gradle compilation of ILRepack with VS2017

### ISSUE THREAD

**Issue by uecasm** [gluck/il-repack#246]
Using the `gradlew msbuild` command line:

    Download https://plugins.gradle.org/m2/com/ullink/gradle/gradle-msbuild-plugin/2.21/gradle-msbuild-plugin-2.21.pom
    Download https://plugins.gradle.org/m2/com/ullink/gradle/gradle-nuget-plugin/2.15/gradle-nuget-plugin-2.15.pom
    Download https://plugins.gradle.org/m2/com/ullink/gradle/gradle-nunit-plugin/1.12/gradle-nunit-plugin-1.12.pom
    Download https://plugins.gradle.org/m2/com/ullink/gradle/gradle-opencover-plugin/1.10/gradle-opencover-plugin-1.10.pom
    Download https://plugins.gradle.org/m2/net/researchgate/gradle-release/2.3.4/gradle-release-2.3.4.pom
    Download https://plugins.gradle.org/m2/net/java/dev/jna/jna/4.2.2/jna-4.2.2.pom
    Download https://plugins.gradle.org/m2/net/java/dev/jna/jna-platform/4.2.2/jna-platform-4.2.2.pom
    Download https://plugins.gradle.org/m2/com/google/guava/guava/16.0.1/guava-16.0.1.pom
    Download https://plugins.gradle.org/m2/com/google/guava/guava-parent/16.0.1/guava-parent-16.0.1.pom
    Download https://plugins.gradle.org/m2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
    Download https://plugins.gradle.org/m2/commons-io/commons-io/2.4/commons-io-2.4.pom
    Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/25/commons-parent-25.pom
    Download https://plugins.gradle.org/m2/org/apache/apache/9/apache-9.pom
    Download https://plugins.gradle.org/m2/de/undercouch/gradle-download-task/3.3.0/gradle-download-task-3.3.0.pom
    Download https://plugins.gradle.org/m2/org/codehaus/gpars/gpars/1.2.1/gpars-1.2.1.pom
    Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.pom
    Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-client/4.5.3/httpcomponents-client-4.5.3.pom
    Download https://plugins.gradle.org/m2/org/apache/httpcomponents/project/7/project-7.pom
    Download https://plugins.gradle.org/m2/org/apache/apache/13/apache-13.pom
    Download https://plugins.gradle.org/m2/org/multiverse/multiverse-core/0.7.0/multiverse-core-0.7.0.pom
    Download https://plugins.gradle.org/m2/org/multiverse/multiverse/0.7.0/multiverse-0.7.0.pom
    Download https://plugins.gradle.org/m2/org/codehaus/jsr166-mirror/jsr166y/1.7.0/jsr166y-1.7.0.pom
    Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.pom
    Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-core/4.4.6/httpcomponents-core-4.4.6.pom
    Download https://plugins.gradle.org/m2/commons-logging/commons-logging/1.2/commons-logging-1.2.pom
    Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/34/commons-parent-34.pom
    Download https://plugins.gradle.org/m2/commons-codec/commons-codec/1.9/commons-codec-1.9.pom
    Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/32/commons-parent-32.pom
    Download https://plugins.gradle.org/m2/com/ullink/gradle/gradle-msbuild-plugin/2.21/gradle-msbuild-plugin-2.21.jar
    Download https://plugins.gradle.org/m2/com/ullink/gradle/gradle-nuget-plugin/2.15/gradle-nuget-plugin-2.15.jar
    Download https://plugins.gradle.org/m2/com/ullink/gradle/gradle-nunit-plugin/1.12/gradle-nunit-plugin-1.12.jar
    Download https://plugins.gradle.org/m2/com/ullink/gradle/gradle-opencover-plugin/1.10/gradle-opencover-plugin-1.10.jar
    Download https://plugins.gradle.org/m2/net/researchgate/gradle-release/2.3.4/gradle-release-2.3.4.jar
    Download https://plugins.gradle.org/m2/net/java/dev/jna/jna/4.2.2/jna-4.2.2.jar
    Download https://plugins.gradle.org/m2/net/java/dev/jna/jna-platform/4.2.2/jna-platform-4.2.2.jar
    Download https://plugins.gradle.org/m2/com/google/guava/guava/16.0.1/guava-16.0.1.jar
    Download https://plugins.gradle.org/m2/commons-io/commons-io/2.4/commons-io-2.4.jar
    Download https://plugins.gradle.org/m2/de/undercouch/gradle-download-task/3.3.0/gradle-download-task-3.3.0.jar
    Download https://plugins.gradle.org/m2/org/codehaus/gpars/gpars/1.2.1/gpars-1.2.1.jar
    Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar
    Download https://plugins.gradle.org/m2/org/multiverse/multiverse-core/0.7.0/multiverse-core-0.7.0.jar
    Download https://plugins.gradle.org/m2/org/codehaus/jsr166-mirror/jsr166y/1.7.0/jsr166y-1.7.0.jar
    Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar
    Download https://plugins.gradle.org/m2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
    Download https://plugins.gradle.org/m2/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
    Error during project file parsing: Microsoft.Build.Exceptions.InvalidProjectFileException: Invalid static method invocation syntax: "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget), $(TargetFrameworkRootPath), $(TargetFrameworkFallbackSearchPaths))".
    Method 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries' not found.
    Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).
       C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets
       at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
       at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
       at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation)
       at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertyBody(String propertyBody, Object propertyValue, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
       at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
       at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
       at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
       at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyElement(ProjectPropertyElement propertyElement)
       at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyGroupElement(ProjectPropertyGroupElement propertyGroupElement)
       at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
       at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
       at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
       at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
       at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
       at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
       at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
       at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
       at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
       at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
       at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
       at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
       at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
       at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
       at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
       at ProjectFileParser.ProjectHelpers.LoadProject(String fullPath, IDictionary`2 args)
       at ProjectFileParser.ProjectHelpers.<>c__DisplayClass0_0.<GetProjects>b__1(ProjectInSolution p)
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at ProjectFileParser.ProjectHelpers.GetProjects(SolutionFile solution, IDictionary`2 args)
       at ProjectFileParser.Program.ParseSolution(String file, JObject args)
       at ProjectFileParser.Program.Parse(String file, JObject args)
       at ProjectFileParser.Program.Main(String[] args)
    Error during project file parsing: Microsoft.Build.Exceptions.InvalidProjectFileException: Invalid static method invocation syntax: "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget), $(TargetFrameworkRootPath), $(TargetFrameworkFallbackSearchPaths))".
    Method 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries' not found.
    Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).
       C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets
       at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
       at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
       at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation)
       at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertyBody(String propertyBody, Object propertyValue, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
       at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
       at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
       at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
       at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyElement(ProjectPropertyElement propertyElement)
       at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyGroupElement(ProjectPropertyGroupElement propertyGroupElement)
       at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
       at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
       at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
       at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
       at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
       at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
       at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
       at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
       at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
       at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
       at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
       at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
       at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
       at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
       at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
       at ProjectFileParser.ProjectHelpers.LoadProject(String fullPath, IDictionary`2 args)
       at ProjectFileParser.ProjectHelpers.<>c__DisplayClass0_0.<GetProjects>b__1(ProjectInSolution p)
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at ProjectFileParser.ProjectHelpers.GetProjects(SolutionFile solution, IDictionary`2 args)
       at ProjectFileParser.Program.ParseSolution(String file, JObject args)
       at ProjectFileParser.Program.Parse(String file, JObject args)
       at ProjectFileParser.Program.Main(String[] args)
    Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
    org.gradle.api.GradleException: Project file parsing failed
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
            at java.lang.reflect.Constructor.newInstance(Unknown Source)
            at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
            at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
            at com.ullink.Msbuild.parseProjectFile(Msbuild.groovy:115)
            at com.ullink.Msbuild$parseProjectFile.callCurrent(Unknown Source)
            at com.ullink.Msbuild.resolveProject(Msbuild.groovy:123)
            at com.ullink.Msbuild.getProjects(Msbuild.groovy:69)
            at com.ullink.Msbuild_Decorated.getProjects(Unknown Source)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
            at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:62)
            at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:166)
            at org.gradle.api.internal.BeanDynamicObject.getProperty(BeanDynamicObject.java:109)
            at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:81)
            at com.ullink.Msbuild_Decorated.getProperty(Unknown Source)
            at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
            at com.ullink.AssemblyInfoVersionPatcher$_closure5$_closure10.doCall(AssemblyInfoVersionPatcher.groovy:30)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
            at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
            at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
            at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
            at groovy.lang.Closure.call(Closure.java:426)
            at groovy.lang.Closure.call(Closure.java:442)
            at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
            at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
            at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:110)
            at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:488)
            at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:58)
            at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
            at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:202)
            at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
            at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
            at org.gradle.api.internal.tasks.RealizableTaskCollection.all(RealizableTaskCollection.java:187)
            at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:126)
            at org.gradle.api.DomainObjectCollection$withType.call(Unknown Source)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
            at com.ullink.AssemblyInfoVersionPatcher$_closure5.doCall(AssemblyInfoVersionPatcher.groovy:29)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
            at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
            at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
            at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
            at groovy.lang.Closure.call(Closure.java:426)
            at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
            at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
            at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
            at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
            at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
            at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
            at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
            at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
            at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
            at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:496)
            at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:87)
            at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
            at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
            at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
            at org.gradle.internal.Factories$1.create(Factories.java:22)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
            at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
            at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
            at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
            at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
            at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
            at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
            at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
            at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
            at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
            at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
            at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
            at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
            at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
            at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
            at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
            at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
            at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
            at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
            at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
            at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
            at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
            at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
            at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
            at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
            at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
            at org.gradle.launcher.Main.doAction(Main.java:33)
            at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
            at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
            at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
            at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
            at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)

    FAILURE: Build failed with an exception.

    * Where:
    Build file 'D:\Drives\il-repack\build.gradle' line: 33

    * What went wrong:
    A problem occurred evaluating root project 'il-repack'.
    > Project file parsing failed

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

It does, however, compile in VS2017 itself using the SLN file...

**Comment by timotei** [comment]
@uecasm Yes, there is an issue with latest MSBuild way of doing things. I will push next week a fix.

**Comment by timotei** [comment]
Fixed by https://github.com/gluck/il-repack/pull/250
