### ISSUE TITLE
Failed to resolve `SecurityPermissionFlag`

### ISSUE THREAD

**Issue by Logerfo** [gluck/il-repack#264]
> Mono.Cecil.ResolutionException: Failed to resolve System.Security.Permissions.SecurityPermissionFlag
at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
at Mono.Cecil.SignatureReader.ReadCustomAttributeEnum(TypeReference enum_type)
at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type)
at Mono.Cecil.SignatureReader.ReadCustomAttributeNamedArgument(Collection'1& fields, Collection'1& properties)
at Mono.Cecil.SignatureReader.ReadCustomAttributeNamedArguments(UInt16 count, Collection'1& fields, Collection'1& properties)
at Mono.Cecil.SignatureReader.ReadSecurityAttribute()
at Mono.Cecil.MetadataReader.ReadSecurityDeclarationSignature(SecurityDeclaration declaration)
at Mono.Cecil.SecurityDeclaration.<Resolve>b__19_0(SecurityDeclaration declaration, MetadataReader reader)
at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func'3 read)
at Mono.Cecil.SecurityDeclaration.Resolve()
at Mono.Cecil.SecurityDeclaration.get_SecurityAttributes()
at Mono.Cecil.ImmediateModuleReader.ReadSecurityDeclarations(ISecurityDeclarationProvider provider)
at Mono.Cecil.ImmediateModuleReader.ReadMethods(TypeDefinition type)
at Mono.Cecil.ImmediateModuleReader.ReadType(TypeDefinition type)
at Mono.Cecil.ImmediateModuleReader.ReadTypes(Collection'1 types)
at Mono.Cecil.ImmediateModuleReader.ReadModule(ModuleDefinition module)
at Mono.Cecil.ImmediateModuleReader.<ReadModule>b__1_0(ModuleDefinition module, MetadataReader reader)
at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func'3 read)
at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
at ILRepacking.ILRepack.ReadInputAssembly(String assembly, Boolean isPrimary)
at ILRepacking.ILRepack.ReadInputAssemblies()
at ILRepacking.ILRepack.Repack()
at ILRepacking.Application.Main(String[] args)

**Comment by Logerfo** [comment]
Solved using `/lib:` argument pointing to native `NETCore.App` libraries.
