### ISSUE TITLE
Mixed assembly, use /zeropekind still raise Writing mixed-mode assemblies is not supported

### ISSUE THREAD

**Issue by alexis-idigo** [gluck/il-repack#324]
Expected behavior, similar to ILMerge would be to just skip the extra data.

Instead we got:
System.NotSupportedException: Writing mixed-mode assemblies is not supported
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at ILRepacking.ILRepack.Repack()
   at ILRepacking.Application.Main(String[] args)

**Comment by alexis-idigo** [comment]
Note: it actually works provided the /zeropekind is set before mixed assembly path is provided ;-)
