### ISSUE TITLE
ArgumentOutOfRange in RepackAssemblyResolver.cs:line 203

### ISSUE THREAD

**Issue by KirillOsenkov** [gluck/il-repack#361]
```
##[error]EXEC(0,0): Error : Failed to load debug information for Microsoft.Mashup.Cdm.dll:
\Microsoft.Mashup.Cdm.dll: [\MashupEngineLibrary45.Core.csproj]
         System.ArgumentOutOfRangeException: Length cannot be less than zero.
         Parameter name: length
            at System.String.Substring(Int32 startIndex, Int32 length)
            at ILRepacking.RepackAssemblyResolver.InitializeDotnetRuntimeDirectories() in /_/ILRepack/RepackAssemblyResolver.cs:line 203
            at ILRepacking.RepackAssemblyResolver.TryResolveFromCore(AssemblyNameReference reference) in /_/ILRepack/RepackAssemblyResolver.cs:line 158
            at ILRepacking.RepackAssemblyResolver.TryResolveFromCoreFixVersion(AssemblyNameReference reference) in /_/ILRepack/RepackAssemblyResolver.cs:line 135
            at ILRepacking.RepackAssemblyResolver.TryResolve(AssemblyNameReference name, ReaderParameters parameters) in /_/ILRepack/RepackAssemblyResolver.cs:line 118
            at ILRepacking.RepackAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters) in /_/ILRepack/RepackAssemblyResolver.cs:line 86
            at Mono.Cecil.MetadataResolver.Resolve(TypeReference type) in /_/Mono.Cecil/MetadataResolver.cs:line 111
            at Mono.Cecil.TypeReference.Resolve() in /_/Mono.Cecil/TypeReference.cs:line 278
            at Mono.Cecil.Mixin.CheckedResolve(TypeReference self) in /_/Mono.Cecil/TypeReference.cs:line 345
            at Mono.Cecil.SignatureReader.ReadCustomAttributeEnum(TypeReference enum_type) in /_/Mono.Cecil/AssemblyReader.cs:line 3696
            at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type) in /_/Mono.Cecil/AssemblyReader.cs:line 3575
            at Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments(CustomAttribute attribute, Collection`1 parameters) in /_/Mono.Cecil/AssemblyReader.cs:line 3500
            at Mono.Cecil.MetadataReader.ReadCustomAttributeSignature(CustomAttribute attribute) in /_/Mono.Cecil/AssemblyReader.cs:line 2570
            at Mono.Cecil.CustomAttribute.<Resolve>b__35_0(CustomAttribute attribute, MetadataReader reader) in /_/Mono.Cecil/CustomAttribute.cs:line 205
            at Mono.Cecil.ModuleDefinition.Read[TItem](TItem item, Action`2 read) in /_/Mono.Cecil/ModuleDefinition.cs:line 955
            at Mono.Cecil.CustomAttribute.Resolve() in /_/Mono.Cecil/CustomAttribute.cs:line 202
            at Mono.Cecil.CustomAttribute.get_ConstructorArguments() in /_/Mono.Cecil/CustomAttribute.cs:line 109
            at Mono.Cecil.ImmediateModuleReader.ReadCustomAttributes(ICustomAttributeProvider provider) in /_/Mono.Cecil/AssemblyReader.cs:line 287
            at Mono.Cecil.ImmediateModuleReader.ReadModule(ModuleDefinition module, Boolean resolve_attributes) in /_/Mono.Cecil/AssemblyReader.cs:line 189
            at Mono.Cecil.ModuleDefinition.Read[TItem](TItem item, Action`2 read) in /_/Mono.Cecil/ModuleDefinition.cs:line 955
            at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters) in /_/Mono.Cecil/AssemblyReader.cs:line 82
            at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters) in /_/Mono.Cecil/ModuleDefinition.cs:line 1130
            at ILRepacking.ILRepack.ReadInputAssembly(String assembly, Boolean isPrimary) in /_/ILRepack/ILRepack.cs:line 142
```

**Comment by KirillOsenkov** [comment]
FYI @JustinSchneiderPBI this should fix the random flakiness we see during builds

**Comment by KirillOsenkov** [comment]
https://www.nuget.org/packages/ILRepack/2.0.32
